name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
      - name: Build and Deploy
        env:
          CI: true
        run: |
          npm run build --if-present
          echo 'domain.com' > build/CNAME
          bash deploy.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
